import { Metadata } from "next";
import LegalPageShell, {
  LegalSection,
  LegalDivider,
  LegalList,
  LegalCallout,
} from "@/components/legal/LegalPageShell";

export const metadata: Metadata = {
  title: "Terms of Service — FrameFinder",
  description: "The rules for using FrameFinder.",
};

export default function TermsPage() {
  return (
    <LegalPageShell
      badge="Legal"
      title="Terms of Service"
      subtitle="By using FrameFinder, you agree to these terms. We've kept them plain and honest."
      lastUpdated="June 2026"
    >
      <LegalCallout>
        <strong>Short version:</strong> Use FrameFinder for educational and research
        purposes. You're responsible for what you submit. AI output may be wrong — apply
        your own judgment. Don't abuse the service. Subscriptions are through Stripe;
        cancel any time.
      </LegalCallout>

      <LegalDivider />

      <LegalSection title="1. Acceptance of Terms">
        <p>
          By accessing or using FrameFinder ("the Service"), you agree to be bound by these
          Terms of Service. If you do not agree, do not use the Service.
        </p>
        <p>
          We reserve the right to update these terms. Continued use after changes are
          posted means you accept the updated terms.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="2. What FrameFinder Is">
        <p>
          FrameFinder is an AI-assisted rhetorical and framing analysis tool designed for
          educational, research, and critical thinking purposes. It analyzes text for
          framing patterns, loaded language, claim quality, logical fallacies, missing
          perspectives, and related rhetorical features.
        </p>
        <p>
          FrameFinder is <strong>not</strong> a fact-checking service, a legal authority,
          a news source, or professional advice of any kind.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="3. Your Responsibilities">
        <p>
          You are solely responsible for the content you submit to FrameFinder. By submitting
          content, you represent that:
        </p>
        <LegalList
          items={[
            "You have the right to share the content with a third-party AI service.",
            "The content does not violate any applicable law or third-party rights.",
            "You are not submitting private personal information about others without their consent.",
            "You are not submitting confidential, privileged, or classified material.",
          ]}
        />
        <p>
          FrameFinder is intended for analysis of publicly available or personally authored
          text — articles, speeches, academic excerpts, essays, and similar materials.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="4. AI Output — Limitations and Disclaimer">
        <p>
          Analysis reports are generated by an AI model (Google Gemini) and may be
          incomplete, inaccurate, or miss important context. AI output reflects patterns
          in the model's training — it is not infallible.
        </p>
        <LegalList
          items={[
            "Reports are not definitive judgments about source quality or reliability.",
            "A 'High Framing Risk' score does not mean a source is false or malicious.",
            "Academic and historical sources may carry strong interpretive lenses that are legitimate.",
            "Always apply your own critical thinking before acting on any report.",
            "FrameFinder is not a substitute for professional legal, medical, financial, or editorial advice.",
          ]}
        />
      </LegalSection>

      <LegalDivider />

      <LegalSection title="5. Prohibited Uses">
        <p>You may not use FrameFinder to:</p>
        <LegalList
          items={[
            "Submit illegal content or content that violates third-party intellectual property rights.",
            "Attempt to bypass, circumvent, or exploit usage limits or access controls.",
            "Automate requests in a way that degrades service for other users (scraping, bots).",
            "Submit malicious content or attempt to attack the service or its infrastructure.",
            "Harass, impersonate, or harm other users.",
            "Use the service for any purpose that violates applicable laws or regulations.",
          ]}
        />
        <p>
          Violation of these terms may result in account suspension or termination without
          notice or refund.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="6. Subscriptions and Payments">
        <p>
          FrameFinder offers a free tier and a Student Pro subscription. Subscriptions are
          billed and managed through <strong>Stripe</strong>. By subscribing, you agree to
          Stripe's terms of service in addition to these.
        </p>
        <LegalList
          items={[
            "A 7-day free trial is offered once per Clerk account on the first Student Pro subscription.",
            "After the trial, billing begins automatically at the then-current subscription price.",
            "You may cancel at any time through the customer portal — no penalty.",
            "See our Refund and Cancellation Policy for details on refunds and access after cancellation.",
          ]}
        />
      </LegalSection>

      <LegalDivider />

      <LegalSection title="7. Service Availability">
        <p>
          We aim to keep FrameFinder running reliably, but we make no guarantee of
          uninterrupted access. The Service may be unavailable due to maintenance,
          infrastructure issues, API provider outages, or other factors beyond our control.
        </p>
        <p>
          We reserve the right to modify, suspend, or discontinue the Service (or any part
          of it) at any time. We will try to provide reasonable notice for significant
          changes.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="8. Limitation of Liability">
        <p>
          FrameFinder is provided "as is" without warranties of any kind, express or
          implied. To the fullest extent permitted by law, we are not liable for:
        </p>
        <LegalList
          items={[
            "Inaccurate, incomplete, or misleading analysis reports.",
            "Decisions you make based on AI-generated reports.",
            "Loss of data, revenue, or business resulting from service interruptions.",
            "Third-party actions including Clerk, Stripe, or Google Gemini API issues.",
          ]}
        />
      </LegalSection>

      <LegalDivider />

      <LegalSection title="9. Account Suspension">
        <p>
          We reserve the right to suspend or terminate accounts that violate these terms,
          abuse the service, or engage in fraudulent activity. In cases of clear violation,
          suspension may occur without prior notice. We are not obligated to provide refunds
          for suspended accounts where a violation has occurred.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="10. Governing Law">
        <p>
          These terms are governed by applicable law. Any disputes will be resolved in
          good faith first; if not, in the applicable jurisdiction. This is an early-stage
          product — we prefer to resolve issues directly before any formal process.
        </p>
        <LegalCallout>
          {/* PLACEHOLDER — update this email before launch */}
          Questions about these terms? Email{" "}
          <a
            href="mailto:support@framefinder.app"
            className="font-semibold text-emerald-700 underline"
          >
            support@framefinder.app
          </a>
          .
        </LegalCallout>
      </LegalSection>
    </LegalPageShell>
  );
}
