import { Metadata } from "next";
import LegalPageShell, {
  LegalSection,
  LegalDivider,
  LegalList,
  LegalCallout,
} from "@/components/legal/LegalPageShell";

export const metadata: Metadata = {
  title: "AI & Educational Use Disclaimer — FrameFinder",
  description: "What FrameFinder's AI analysis does and doesn't mean.",
};

export default function AiDisclaimerPage() {
  return (
    <LegalPageShell
      badge="Disclaimer"
      title="AI & Educational Use Disclaimer"
      subtitle="Read this before interpreting your analysis report. It matters."
      lastUpdated="June 2026"
    >
      <LegalCallout>
        <strong>The single most important thing:</strong> FrameFinder detects possible
        framing patterns and rhetorical indicators. It does <strong>not</strong> determine
        whether a source is true, reliable, or good. A "High Framing Risk" score is not an
        accusation — it's a signal to read more carefully.
      </LegalCallout>

      <LegalDivider />

      <LegalSection title="What FrameFinder Does">
        <p>
          FrameFinder analyzes text for rhetorical and framing features, including:
        </p>
        <LegalList
          items={[
            "Framing patterns — how the text positions its subject and guides interpretation.",
            "Loaded language — words or phrases that carry strong implicit value judgments.",
            "Claim quality — whether specific assertions are well-supported, weak, or unsupported.",
            "Logical fallacies — reasoning patterns that may be misleading or invalid.",
            "Missing perspectives — voices, data points, or viewpoints absent from the text.",
            "Neutral rewrite suggestions — alternative phrasings that reduce framing.",
            "Socratic questions — prompts to help you think critically about the text.",
          ]}
        />
        <p>
          These outputs are generated by an AI model (Google Gemini) based on patterns in
          the text and the model's training. They are a starting point for analysis — not
          a final verdict.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="What FrameFinder Does NOT Do">
        <LegalList
          items={[
            "Does not fact-check claims against an external database of verified facts.",
            "Does not determine whether a source is credible, reputable, or trustworthy.",
            "Does not render a verdict on whether a source is 'biased' in a definitive sense.",
            "Does not provide legal, medical, financial, journalistic, or professional editorial advice.",
            "Does not replace human critical thinking, domain expertise, or editorial judgment.",
          ]}
        />
      </LegalSection>

      <LegalDivider />

      <LegalSection title="Understanding Framing Risk">
        <p>
          <strong>Framing risk is not a reliability score.</strong> All writing involves
          framing — the author's choices about what to include, what to emphasize, and what
          language to use. Framing risk measures how strongly a text guides interpretation
          through these choices.
        </p>
        <LegalList
          items={[
            "Low framing risk = the text is primarily explanatory; language is measured; major perspectives are represented.",
            "Medium framing risk = the text has a noticeable interpretive lens; some perspectives are underrepresented.",
            "High framing risk = the text is strongly persuasive; loaded language is frequent; critical perspectives may be absent.",
          ]}
        />
        <p>
          A highly-framed text can still be factually accurate. A low-framing text can still
          contain errors. Framing risk tells you how much the text is working to guide your
          conclusions — not whether those conclusions are correct.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="Academic and Historical Sources">
        <p>
          Academic writing, textbooks, and historical analysis often use strong evaluative
          language that reflects scholarly consensus rather than rhetorical manipulation.
          Phrases like "forced labor," "systematic exploitation," or "unprecedented mortality"
          in a history text are typically evidence-grounded descriptions, not propaganda.
        </p>
        <p>
          FrameFinder is designed to recognize this distinction, but AI models are
          imperfect. If you receive a Medium or High framing risk score on an academic or
          historical source, read the explanation carefully — the AI should distinguish
          between interpretive framing and manipulative rhetoric. If it doesn't, trust your
          domain knowledge.
        </p>
        <p>
          <strong>Academic sources can have a lens and still be good scholarship.</strong>{" "}
          A critical history of colonialism is not biased the same way an advertisement is
          biased. FrameFinder aims to describe the lens, not condemn it.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="AI Limitations">
        <p>
          The analysis is generated by Google's Gemini AI model. AI models:
        </p>
        <LegalList
          items={[
            "May misidentify framing patterns or miss important rhetorical context.",
            "May produce inconsistent results on the same text at different times.",
            "Have knowledge cutoffs and may lack context on recent events or highly specialized topics.",
            "May reflect biases present in their training data.",
            "Are not aware of authorial intent, publication context, or audience.",
          ]}
        />
        <p>
          Always treat the report as one input among many, not as the authoritative
          analysis of the text.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="Intended Use">
        <p>FrameFinder is designed for:</p>
        <LegalList
          items={[
            "Students learning to read critically — AP Language, AP Government, debate, MUN research.",
            "Researchers vetting sources for rhetorical patterns before citing them.",
            "Educators creating discussion prompts and critical thinking exercises.",
            "Journalists and readers who want a structured starting point for source evaluation.",
          ]}
        />
        <p>
          It is <strong>not</strong> designed to be used as a definitive arbiter of source
          quality, a tool for discrediting individuals or organizations, or a replacement
          for professional editorial, legal, or research judgment.
        </p>
      </LegalSection>

      <LegalDivider />

      <LegalSection title="Your Responsibility as a Reader">
        <p>
          Every analysis report should prompt more critical reading — not less. The goal
          is to give you better questions, not replace your answers. Before drawing
          conclusions based on a FrameFinder report:
        </p>
        <LegalList
          items={[
            "Read the original source in full, not just the excerpts highlighted in the report.",
            "Consider the source's context: who wrote it, for whom, and when.",
            "Verify important factual claims independently using authoritative sources.",
            "Consult domain experts or additional sources when the stakes are high.",
            "Treat the AI's framing analysis as a hypothesis, not a conclusion.",
          ]}
        />
      </LegalSection>
    </LegalPageShell>
  );
}
